"""Add human override flag

Revision ID: 94bd77c5d6e7
Revises: 005_add_validation_fields
Create Date: 2026-05-24 19:42:34.077646

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "94bd77c5d6e7"
down_revision = "005_add_validation_fields"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_results",
        sa.Column(
            "is_human_overridden",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_results", "is_human_overridden")
    # ### end Alembic commands ###
